// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOuCm30cYhRr7xbe9tQst_9qvfQXvEcs',
    appId: '1:798680923756:web:7d0bafe268c7471f2ce249',
    messagingSenderId: '798680923756',
    projectId: 'tiktok-tutorial-5e866',
    authDomain: 'tiktok-tutorial-5e866.firebaseapp.com',
    storageBucket: 'tiktok-tutorial-5e866.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Iw2cr9Ic5vmJzMneedTw73pAFrlN11s',
    appId: '1:798680923756:android:cd5456ddd9f1722a2ce249',
    messagingSenderId: '798680923756',
    projectId: 'tiktok-tutorial-5e866',
    storageBucket: 'tiktok-tutorial-5e866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFphT62mVIlJJEBrbEspHAWqyaPBT-JpI',
    appId: '1:798680923756:ios:d7daf0b373728cb32ce249',
    messagingSenderId: '798680923756',
    projectId: 'tiktok-tutorial-5e866',
    storageBucket: 'tiktok-tutorial-5e866.appspot.com',
    iosBundleId: 'com.example.hostapp',
  );
}
